apiVersion: kube.cloud.ovh.upbound.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: kube/v1alpha1/nodepool
  labels:
    testing.upbound.io/example-name: pool
  name: pool
spec:
  forProvider:
    desiredNodes: 3
    flavorName: b2-7
    kubeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    maxNodes: 3
    minNodes: 3
    name: my-pool
    serviceName: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    template:
    - metadata:
      - annotations:
          k1: v1
          k2: v2
        finalizers:
        - F1
        - F2
        labels:
          k3: v3
          k4: v4
      spec:
      - taints:
        - effect: PreferNoSchedule
          key: k
          value: v
        unschedulable: false

---

